[package]
name = "comodoro"
description = "CLI to manage timers"
version = "1.0.0"
authors = ["Clément DOUIN (soywod) <pimalaya.org@posteo.net>"]
rust-version = "1.89"
edition = "2024"
license = "MIT OR Apache-2.0"
categories = ["command-line-utilities", "date-and-time", "no-std"]
keywords = ["pomodoro", "timer", "jsonrpc", "no-std", "cli"]
homepage = "https://pimalaya.org"
documentation = "https://docs.rs/comodoro/latest/comodoro"
repository = "https://github.com/pimalaya/comodoro"

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[features]
default = ["client", "server", "cli", "notify"]
client = ["dep:anyhow"]
server = ["dep:anyhow"]
cli = ["client", "server", "dep:clap", "dep:convert_case", "dep:pimalaya-cli", "dep:pimalaya-config"]
notify = ["cli", "dep:notify-rust", "notify-rust/d"]
vendored = ["notify-rust?/d_vendored"]

[[bin]]
name = "comodoro"
path = "src/main.rs"
required-features = ["cli"]

[[test]]
name = "timer"
path = "tests/timer.rs"
required-features = ["client", "server"]

[[test]]
name = "config"
path = "tests/config.rs"
required-features = ["cli"]

[[example]]
name = "timer"
path = "examples/timer.rs"

[[example]]
name = "client-server"
path = "examples/client_server.rs"
required-features = ["client", "server"]

[profile.release]
lto = "fat"
codegen-units = 1
strip = "symbols"
panic = "abort"

[build-dependencies]
pimalaya-cli = { version = "0.2", default-features = false, features = ["build"], optional = true }

[dependencies]
anyhow = { version = "1", default-features = false, features = ["std"], optional = true }
clap = { version = "4.4", default-features = false, features = ["derive", "error-context", "help", "std", "usage", "wrap_help"], optional = true }
convert_case = { version = "0.11", default-features = false, optional = true }
log = { version = "0.4", default-features = false }
notify-rust = { version = "4", default-features = false, optional = true }
pimalaya-cli = { version = "0.2", default-features = false, features = ["terminal"], optional = true }
pimalaya-config = { version = "0.1", default-features = false, features = ["toml", "secret"], optional = true }
serde = { version = "1", default-features = false, features = ["derive", "alloc"] }
serde_json = { version = "1", default-features = false, features = ["alloc"] }

[target.'cfg(windows)'.dependencies]
uds_windows = { version = "1", default-features = false }

[dev-dependencies]
toml = { version = "1.1", default-features = false, features = ["parse", "serde", "std"] }
